server:
  port: 10222
spring:
  application:
    name: consumer-client




# 注册中心地址
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10211/eureka/
  instance:
    prefer-ip-address: true
